export default {
  Accordion: "import {Accordion} from '@site/src/components';",
  AccordionGroup: "import {AccordionGroup} from '@site/src/components';",
  APICard: "import {APICard} from '@site/src/components';",
  Card: "import {Card} from '@site/src/components';",
  CardList: "import {CardList} from '@site/src/components';",
  Request: "import {Request} from '@site/src/components';",
  Response: "import {Response} from '@site/src/components';",
  Image: "import {Image} from '@site/src/components';",
  Callout: "import {Callout} from '@site/src/components';",
  Searchbar: "import {Searchbar} from '@site/src/components';",
  Tab: "import {Tab} from '@site/src/components';",
  TabItem: "import {TabItem} from '@site/src/components';",
  Tabs: "import {Tabs} from '@site/src/components';",
  Video: "import {Video} from '@site/src/components';",
};
