export default {
  Accordion: "import {Accordion} from '@site/src/components';",
  AccordionGroup: "import {AccordionGroup} from '@site/src/components';",
  APICard: "import {APICard} from '@site/src/components';",
  Card: "import {Card} from '@site/src/components';",
  CardList: "import {CardList} from '@site/src/components';",
  Request: "import {Request} from '@site/src/components';",
  Response: "import {Response} from '@site/src/components';",
  Image: "import {Image} from '@site/src/components';",
  Callout: "import {Callout} from '@site/src/components';",
  Searchbar: "import {Searchbar} from '@site/src/components';",
  TabItem: "import {TabItem} from '@site/src/components';",
  Tabs: "import {Tabs} from '@site/src/components';",
  Video: "import {Video} from '@site/src/components';",
  // ApiTabs: "import ApiTabs from '@theme/ApiTabs';",
  // DiscriminatorTabs: "import DiscriminatorTabs from '@theme/DiscriminatorTabs';",
  // Heading: "import Heading from '@theme/Heading';",
  // MethodEndpoint: "import MethodEndpoint from '@theme/ApiExplorer/MethodEndpoint';",
  // MimeTabs: "import MimeTabs from '@theme/MimeTabs';",
  // OperationTabs: "import OperationTabs from '@theme/OperationTabs';",
  // ParamsItem: "import ParamsItem from '@theme/ParamsItem';",
  // ResponseSamples: "import ResponseSamples from '@theme/ResponseSamples';",
  // SchemaItem: "import SchemaItem from '@theme/SchemaItem';",
  // SchemaTabs: "import SchemaTabs from '@theme/SchemaTabs';",
  // SecuritySchemes: "import SecuritySchemes from '@theme/ApiExplorer/SecuritySchemes';",
  // ParamsDetails: "import ParamsDetails from '@theme/ParamsDetails';",
  // RequestSchema: "import RequestSchema from '@theme/RequestSchema';",
  // StatusCodes: "import StatusCodes from '@theme/StatusCodes';",
};
